### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by Poussinou**
Here it is, I don't know if you're able to put a system to switch the language, but I hope so ;)
If no, I'm sorry for the pull request^^

### CODE REVIEW

**Comment by waelk10** [comment]
This isn't a current priority, but if I have enough time, I'll see if I can implement it soon.
Though honestly, even if I implement the system I'm not willing to do the translations, still, I'll try to implement a basic system, in case I do implement the system, I won't provide the translations! If anyone willing to contribute them I'll put them in!

**Comment by waelk10** [comment]
I'll push the changes, currently I implemented the french translations that you gave!

**Comment by Poussinou** [comment]
good work thanks ;)

I don't understand what you mean with -fr suffix

**Comment by waelk10** [comment]
Forget about that, stupid and sleepy me was going to manually implement code for the different translations!

**Pull request closed without merging**
